#!/bin/bash

LICENSE=$(cat LICENSE)

DATA=$(cat << ENDSTR
package text

// Code generated by gen-license.sh. DO NOT EDIT.

// License contains the license text for usql.
var License = \`$LICENSE\`
ENDSTR
)

echo "$DATA" > text/license.go
