// +build all,!no_avatica most,!no_avatica avatica,!no_avatica

package internal

// Code generated by gen.go. DO NOT EDIT.

import (
	_ "github.com/xo/usql/drivers/avatica" // Apache Avatica driver
)
