// +build all,!no_bigquery most,!no_bigquery bigquery,!no_bigquery

package internal

// Code generated by gen.sh. DO NOT EDIT.

import (
	_ "github.com/xo/usql/drivers/bigquery" // bigquery driver
)
