// +build all,!no_bigquery most,!no_bigquery bigquery,!no_bigquery

package internal

// Code generated by gen.sh. DO NOT EDIT.

import (
	// bigquery driver
	_ "github.com/xo/usql/drivers/bigquery"
)
