// +build all,!no_bigquery most,!no_bigquery bigquery,!no_bigquery

package internal

// Code generated by gen.go. DO NOT EDIT.

import (
	_ "github.com/xo/usql/drivers/bigquery" // Google BigQuery driver
)
