// +build all,!no_cassandra most,!no_cassandra cassandra,!no_cassandra

package internal

// Code generated by gen.sh. DO NOT EDIT.

import (
	// cassandra driver
	_ "github.com/xo/usql/drivers/cassandra"
)
