// +build all,!no_clickhouse most,!no_clickhouse clickhouse,!no_clickhouse

// Code generated by gen.sh. DO NOT EDIT.

package internal

import (
	// clickhouse driver
	_ "github.com/knq/usql/drivers/clickhouse"
)
