// +build all,!no_clickhouse most,!no_clickhouse clickhouse,!no_clickhouse

package internal

// Code generated by gen.sh. DO NOT EDIT.

import (
	_ "github.com/xo/usql/drivers/clickhouse" // clickhouse driver
)
