// +build all,!no_couchbase most,!no_couchbase couchbase,!no_couchbase

package internal

// Code generated by gen.sh. DO NOT EDIT.

import (
	// couchbase driver
	_ "github.com/xo/usql/drivers/couchbase"
)
