// +build all,!no_couchbase most,!no_couchbase couchbase,!no_couchbase

// Code generated by gen.sh. DO NOT EDIT.

package internal

import (
	// couchbase driver
	_ "github.com/knq/usql/drivers/couchbase"
)
