// +build all,!no_firebird most,!no_firebird firebird,!no_firebird

package internal

// Code generated by gen.sh. DO NOT EDIT.

import (
	// firebird driver
	_ "github.com/xo/usql/drivers/firebird"
)
