// +build all,!no_firebird most,!no_firebird firebird,!no_firebird

package internal

// Code generated by gen.sh. DO NOT EDIT.

import (
	_ "github.com/xo/usql/drivers/firebird" // firebird driver
)
