// +build all,!no_firebird most,!no_firebird firebird,!no_firebird

// Code generated by gen.sh. DO NOT EDIT.

package internal

import (
	// firebird driver
	_ "github.com/knq/usql/drivers/firebird"
)
