// Package internal provides a way to obtain information about which database
// drivers were included at build.
package internal

// Code generated by gen.go. DO NOT EDIT.

// KnownBuildTags returns a map of known driver names to its respective build
// tags.
func KnownBuildTags() map[string]string {
	return map[string]string{
		"athena":        "awsathena",     // github.com/uber/athenadriver/go
		"avatica":       "avatica",       // github.com/apache/calcite-avatica-go/v5
		"bigquery":      "bigquery",      // gorm.io/driver/bigquery/driver
		"cassandra":     "cql",           // github.com/xo/cql
		"chai":          "chai",          // github.com/chaisql/chai
		"clickhouse":    "clickhouse",    // github.com/ClickHouse/clickhouse-go/v2
		"cosmos":        "cosmos",        // github.com/btnguyen2k/gocosmos
		"couchbase":     "couchbase",     // github.com/xo/dbimp/couchbase
		"csvq":          "csvq",          // github.com/mithrandie/csvq-driver
		"databend":      "databend",      // github.com/datafuselabs/databend-go
		"databricks":    "databricks",    // github.com/databricks/databricks-sql-go
		"duckdb":        "duckdb",        // github.com/duckdb/duckdb-go/v2
		"dynamodb":      "godynamo",      // github.com/btnguyen2k/godynamo
		"exasol":        "exasol",        // github.com/exasol/exasol-driver-go
		"firebird":      "firebirdsql",   // github.com/nakagami/firebirdsql
		"flightsql":     "flightsql",     // github.com/apache/arrow-go/v18/arrow/flight/flightsql/driver
		"godror":        "godror",        // github.com/godror/godror
		"h2":            "h2",            // github.com/jmrobles/h2go
		"hive":          "hive",          // github.com/beltran/gohive/v2
		"impala":        "impala",        // github.com/sclgo/impala-go
		"libpq":         "postgres",      // github.com/lib/pq
		"maxcompute":    "maxcompute",    // github.com/aliyun/aliyun-odps-go-sdk/sqldriver
		"moderncsqlite": "moderncsqlite", // modernc.org/sqlite
		"mysql":         "mysql",         // github.com/go-sql-driver/mysql
		"netezza":       "nzgo",          // github.com/IBM/nzgo/v12
		"odbc":          "odbc",          // github.com/alexbrainman/odbc
		"oracle":        "oracle",        // github.com/sijms/go-ora/v3
		"ots":           "ots",           // github.com/aliyun/aliyun-tablestore-go-sql-driver
		"pgx":           "pgx",           // github.com/jackc/pgx/v5/stdlib
		"presto":        "presto",        // github.com/prestodb/presto-go-client/v2
		"ql":            "ql",            // modernc.org/ql
		"saphana":       "hdb",           // github.com/SAP/go-hdb/driver
		"snowflake":     "snowflake",     // github.com/snowflakedb/gosnowflake/v2
		"spanner":       "spanner",       // github.com/googleapis/go-sql-spanner
		"sqlite3":       "sqlite3",       // github.com/mattn/go-sqlite3
		"sqlserver":     "sqlserver",     // github.com/microsoft/go-mssqldb
		"surrealdb":     "surrealdb",     // github.com/xo/dbimp/surrealdb
		"trino":         "trino",         // github.com/trinodb/trino-go-client/trino
		"vertica":       "vertica",       // github.com/vertica/vertica-sql-go
		"voltdb":        "voltdb",        // github.com/VoltDB/voltdb-client-go/voltdbclient
		"ydb":           "ydb",           // github.com/ydb-platform/ydb-go-sdk/v3
		"postgres":      "pgx",           // github.com/jackc/pgx/v5/stdlib
	}
}
