// +build all,!no_maxcompute most,!no_maxcompute maxcompute,!no_maxcompute

package internal

// Code generated by gen.sh. DO NOT EDIT.

import (
	_ "github.com/xo/usql/drivers/maxcompute" // maxcompute driver
)
