// +build all,!no_moderncsqlite most,!no_moderncsqlite moderncsqlite,!no_moderncsqlite

package internal

// Code generated by gen.sh. DO NOT EDIT.

import (
	_ "github.com/xo/usql/drivers/moderncsqlite" // moderncsqlite driver
)
