// +build all,!no_mymysql most,!no_mymysql mymysql,!no_mymysql

package internal

// Code generated by gen.go. DO NOT EDIT.

import (
	_ "github.com/xo/usql/drivers/mymysql" // MySQL MyMySQL driver
)
