// +build all,!no_postgres most,!no_postgres postgres,!no_postgres

package internal

// Code generated by gen.go. DO NOT EDIT.

import (
	_ "github.com/xo/usql/drivers/postgres" // PostgreSQL driver
)
