// +build all,!no_snowflake most,!no_snowflake snowflake,!no_snowflake

package internal

// Code generated by gen.sh. DO NOT EDIT.

import (
	// snowflake driver
	_ "github.com/xo/usql/drivers/snowflake"
)
