// +build all,!no_spanner most,!no_spanner spanner,!no_spanner

package internal

// Code generated by gen.go. DO NOT EDIT.

import (
	_ "github.com/xo/usql/drivers/spanner" // Google Spanner driver
)
