// +build all,!no_sqlserver most,!no_sqlserver sqlserver,!no_sqlserver

package internal

// Code generated by gen.go. DO NOT EDIT.

import (
	_ "github.com/xo/usql/drivers/sqlserver" // Microsoft SQL Server driver
)
